#!/bin/bash
#PBS -S /bin/bash
#PBS -j oe
#PBS -V
#PBS -l nodes=1:ppn=8:gpus=1
project_dir=/home/xyzhang/research/ADFPEPS.jl
julia --project=${project_dir} ${project_dir}/project/Hubbard.jl --D 4 --chi 30 --t 1 --U 12 --mu 8 --folder ~/../../data1/xyzhang/ADFPEPS/Hubbard/